# Multi-stage build for all Luminary Handbook client images

FROM mhart/alpine-node:14 AS client-base
# install dependencies
WORKDIR /app
COPY storybook/package*.json /app/storybook/
WORKDIR /app/storybook
RUN npm ci
# Copy all local files into the image.
COPY /client/src /app/storybook/src
COPY /client/static /app/storybook/static
COPY /storybook/.storybook /app/storybook/.storybook
COPY /storybook/docker.env /app/storybook/.env
COPY /storybook/jsconfig.json /app/storybook/jsconfig.json
COPY /storybook/svelte.config.js /app/storybook/svelte.config.js
#RUN node node_modules/esbuild/install.js
RUN npm run build-storybook -- -o ./build
###
# Only copy over the Node pieces we need
###
FROM mhart/alpine-node:slim-14 AS storybook
WORKDIR /app
COPY --from=client-base /app /app
#COPY /client .
EXPOSE $PORT
CMD ["node", "--max_old_space_size=4096", "./build"]
